/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.instancio.generators;

import org.instancio.Generator;
import org.instancio.GeneratorContext;
import org.instancio.internal.random.RandomProvider;

/**
 * Base class for generators that produce random values.
 *
 * @param <T> type generated by this generator
 */
public abstract class AbstractRandomGenerator<T> implements Generator<T> {

    private final GeneratorContext context;

    protected AbstractRandomGenerator(final GeneratorContext context) {
        this.context = context;
    }

    public GeneratorContext getContext() {
        return context;
    }

    protected RandomProvider random() {
        return context.random();
    }
}
