package org.instancio.generators;

import org.instancio.Generator;
import org.instancio.internal.random.RandomProvider;

/**
 * Base class for generators that produce random values.
 *
 * @param <T> type generated by this generator
 */
public abstract class AbstractRandomGenerator<T> implements Generator<T> {

    private final RandomProvider random;

    protected AbstractRandomGenerator(final RandomProvider random) {
        this.random = random;
    }

    /**
     * The {@link RandomProvider} needs to be used to ensure values
     * are generated with a consistent seed. This allows generation
     * to be repeatable.
     */
    protected RandomProvider random() {
        return random;
    }
}
