package org.instancio.generators;

import org.instancio.Generator;
import org.instancio.internal.model.ModelContext;
import org.instancio.internal.random.RandomProvider;

/**
 * Base class for generators that produce random values.
 *
 * @param <T> type generated by this generator
 */
public abstract class AbstractRandomGenerator<T> implements Generator<T> {

    private final ModelContext<?> context;

    protected AbstractRandomGenerator(final ModelContext<?> context) {
        this.context = context;
    }

    public ModelContext<?> getContext() {
        return context;
    }

    /**
     * The {@link RandomProvider} needs to be used to ensure values
     * are generated with a consistent seed. This allows generation
     * to be repeatable.
     */
    protected RandomProvider random() {
        return context.getRandomProvider();
    }
}
