/*
 * Copyright 2022-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.instancio.protobuf.internal.spi;

import com.google.protobuf.ByteString;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.Duration;
import com.google.protobuf.Message;
import com.google.protobuf.ProtocolMessageEnum;
import com.google.protobuf.Timestamp;
import org.instancio.Node;
import org.instancio.generator.Generator;
import org.instancio.generator.GeneratorContext;
import org.instancio.generator.GeneratorSpec;
import org.instancio.generators.Generators;
import org.instancio.internal.generator.InternalGeneratorContext;
import org.instancio.internal.util.StringUtils;
import org.instancio.protobuf.internal.generator.ProtoByteStringGenerator;
import org.instancio.protobuf.internal.generator.ProtoDurationGenerator;
import org.instancio.protobuf.internal.generator.ProtoEnumGenerator;
import org.instancio.protobuf.internal.generator.ProtoMessageBuilderGenerator;
import org.instancio.protobuf.internal.generator.ProtoTimestampGenerator;
import org.instancio.protobuf.internal.generator.ProtoUnsignedIntGenerator;
import org.instancio.protobuf.internal.generator.ProtoUnsignedLongGenerator;
import org.instancio.settings.Settings;
import org.instancio.spi.InstancioServiceProvider;
import org.instancio.spi.ServiceProviderContext;
import org.jspecify.annotations.Nullable;

import java.lang.reflect.Field;

class ProtoGeneratorProvider implements InstancioServiceProvider.GeneratorProvider {

    private final GeneratorContext generatorContext;

    ProtoGeneratorProvider(final ServiceProviderContext spContext) {
        this.generatorContext = new InternalGeneratorContext(spContext.settings(), spContext.random());
    }

    @Nullable
    @Override
    public GeneratorSpec<?> getGenerator(final Node node, final Generators generators) {
        final Field field = node.getField();
        final Field protoField = field != null ? field : getParentField(node);

        if (protoField != null) {
            final FieldDescriptor fd = getProtoFieldDescriptor(protoField);
            final GeneratorSpec<?> spec = fd == null ? null : getUnsignedGenerator(fd, node);

            if (spec != null) {
                return spec;
            }
        }
        return getGeneratorSpecForClass(node.getTargetClass());
    }

    @Nullable
    private static Field getParentField(final Node node) {
        final Node parent = node.getParent();
        return parent == null ? null : parent.getField();
    }

    @Nullable
    private Generator<?> getGeneratorSpecForClass(final Class<?> target) {
        if (target == Timestamp.class) {
            return new ProtoTimestampGenerator();
        }
        if (target == Duration.class) {
            return new ProtoDurationGenerator();
        }
        if (Message.class.isAssignableFrom(target)) {
            return new ProtoMessageBuilderGenerator(target);
        }
        if (ProtocolMessageEnum.class.isAssignableFrom(target)) {
            return new ProtoEnumGenerator(target);
        }
        if (ByteString.class.isAssignableFrom(target)) {
            return new ProtoByteStringGenerator(generatorContext);
        }
        return null;
    }

    @Nullable
    private GeneratorSpec<?> getUnsignedGenerator(final FieldDescriptor fd, final Node node) {
        final boolean isFieldNode = node.getField() != null;
        final boolean isScalar = !fd.isRepeated();

        // A scalar field is generated by its own node, whereas a repeated or map
        // field is generated by its element/value node (where isFieldNode is false).
        if (isFieldNode != isScalar) {
            return null;
        }

        // For a map field, resolve the node to its key or value side,
        // otherwise use the field's own type.
        final FieldDescriptor.Type protoType = fd.isMapField()
                ? getMapEntryType(fd, node.getTargetClass())
                : fd.getType();

        if (protoType == null) {
            return null;
        }

        final Settings settings = generatorContext.settings();

        if (protoType == FieldDescriptor.Type.UINT32
                || protoType == FieldDescriptor.Type.FIXED32) {

            return new ProtoUnsignedIntGenerator(settings);
        }

        if (protoType == FieldDescriptor.Type.UINT64
                || protoType == FieldDescriptor.Type.FIXED64) {

            return new ProtoUnsignedLongGenerator(settings);
        }

        return null;
    }

    /**
     * Returns the unsigned type of the map key or value side that corresponds
     * to the given target class, or {@code null} if neither side is unsigned.
     *
     * <p>A map's key and value are both element nodes with no backing field, so
     * they are indistinguishable through {@link Node} except by target class
     * ({@code Integer} or {@code Long}). A map whose key and value share a boxed
     * Java type but differ in signedness (e.g. {@code map<int32, uint32>})
     * is not supported.
     */
    private static FieldDescriptor.@Nullable Type getMapEntryType(
            final FieldDescriptor fd,
            final Class<?> targetClass) {

        final FieldDescriptor keyFd = fd.getMessageType().findFieldByName("key");
        final FieldDescriptor valueFd = fd.getMessageType().findFieldByName("value");

        if (targetClass == Integer.class) {
            if (isUnsignedIntType(keyFd.getType())) {
                return keyFd.getType();
            }
            if (isUnsignedIntType(valueFd.getType())) {
                return valueFd.getType();
            }
        } else if (targetClass == Long.class) {
            if (isUnsignedLongType(keyFd.getType())) {
                return keyFd.getType();
            }
            if (isUnsignedLongType(valueFd.getType())) {
                return valueFd.getType();
            }
        }
        return null;
    }

    private static boolean isUnsignedIntType(final FieldDescriptor.Type type) {
        return type == FieldDescriptor.Type.UINT32 || type == FieldDescriptor.Type.FIXED32;
    }

    private static boolean isUnsignedLongType(final FieldDescriptor.Type type) {
        return type == FieldDescriptor.Type.UINT64 || type == FieldDescriptor.Type.FIXED64;
    }

    @Nullable
    private static FieldDescriptor getProtoFieldDescriptor(final Field field) {
        final Class<?> declaringClass = field.getDeclaringClass();
        if (!ProtoHelper.isProtoMessage(declaringClass)) {
            return null;
        }

        final String fieldName = field.getName();

        final String protoFieldName = StringUtils.camelCaseToSnakeCase(
                fieldName.substring(0, fieldName.length() - 1));

        return ProtoHelper
                .getDescriptor(declaringClass)
                .findFieldByName(protoFieldName);
    }
}
