== Introduction

=== Overview

Instancio is a Java library for generating test objects.
Its main goal is to reduce the amount of manual data setup in unit tests.
Its API was designed to be as non-intrusive and as concise as possible, while providing enough flexibility to customise generated objects.
Instancio requires no changes to production code, and it can be used out-of-the-box with zero configuration.

=== Project Goals

There are several existing libraries for generating realistic test data, such as addresses, first and last names, and so on.
While Instancio also supports this use case, this is not its goal.
The idea behind the project is that most unit tests do not care about the actual values.
They just require the _presence of a value_.
Therefore, the main goal of Instancio is simply to generate fully populated objects with random data, including arrays, collections, nested collections, generic types, and so on.
And it aims to do so with as little code as possible in order to keep the tests concise.

Another goal of Instancio is to make the tests more dynamic.
Since each test run is against random values, the tests become alive.
They cover a wider range of inputs, which might help uncover bugs that may have gone unnoticed with static data.

Finally, Instancio aims to provide reproducible data.
It uses a consistent seed value for each object graph it generates.
Therefore, if a test fails against a given set of inputs, Instancio supports re-generating the same data set in order to reproduce the failed test.
